### ISSUE TITLE
OutOfMemoryException in Input#readUTF8String

### ISSUE THREAD

**Issue by saket** [caffeine-mgn/pw.binom.io#16]
This code results in an OOM because `Input#readUTF8String` tries to allocate a `StringBuilder` of huge size. I wasn't able to investigate much, but it looks like `Input.readInt` isn't correctly reading the size of a buffer.

```kotlin
ByteBuffer.alloc(DEFAULT_BUFFER_SIZE).use {
  return file.read().readUTF8String(it)
}
```

**Comment by caffeine-mgn** [comment]
Input#readUTF8String reads utf-8 string with specific format: 4 bytes - length of utf-8 string, other bytes - string
Perhaps first 4 bytes is big integer.

If you want to read simple text from file you can use this code:
```
    File("file.txt").read().reader(Charsets.UTF8).use { 
        it.readText()
    }
```

**Comment by saket** [comment]
By `simple text` are you asking if my file content is small enough?

**Comment by caffeine-mgn** [comment]
> By `simple text` are you asking if my file content is small enough?

I mean do you use special binary format or just text (like *.txt)?
`readUTF8String` - must be use for special binar format since it read 4 bytes signed value as length of string and then the string in utf-8 charset

I mean if you try to read simple text using readUTF8String it will read first 4 bytes (4 chars?) as int, and then it try to alloc memory for this length. And then you will got OutOfMemoryException :)

**Comment by saket** [comment]
Ah, gotcha. That wasn't obvious from the function name.
